// <auto-generated />
namespace MvcBookStore.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddAuthorToBook : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201204022316306_AddAuthorToBook"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/soy8up0+q6u3rtqrz8Xfzyfhp1maTrMk/So/LIiOEXufl+Xtit/MQ2H1k+6WeTwnD9vrN9Srn3j/7CL36LajN75VfBx/QRy/rapXX7fWr/Nx772z2UXo3fPdu92X7auc9oPDZR2fL9t7eR+mLdVlmk5I+OM9KjHn16SMmxef5Mq+zNp+9zNo2r2mOzmY5D0FJ8Wj16e2o8fDuzh6ocTdbLqs2a2nCe8h3UH1TtGVuMH3d1sQ8H6XPinf57Hm+vGjnFtsvsnfmE/r1o/SrZUG8Ri+19Tr3Ryd/b+71eN3Oq/pmEnWgvMguiwseVhTeR+mrvOSvm3mxEm4aYy5+f/P9s7pavKrQgffx7/+6WtdTEKHqf/cmqy/yNsTk8V3HYRv5Trv9GpznCPS+vHdb0v6/gvueFXXT4tcfOgc+z34oHQ+xynHTVNOCaeTpDMOnIeany1m6gWkFfcPqhO26bItVWUyp288++laPEHFwhs89cEZoQoC7IXYE8Mvl07zM2zw9nrZsYk6yZprN+lNAtJiFnxDD5zW4LSvJkDRtnRXLti8dxXJarLJyGO3OK+8lUkDMdtH95mm+ypeQh+EZ+NC+bRcdYt1Em8d3PSbqqyF6p6U38lpR8I3v0wm+zd91CKdvvs5bjyebj1LHwgGj9fgqfFnGHHvdMFYHgDecEAWrvr0WEe3epexmubHo2mH2pmazpHgA7FC7DB8OKaIX7CzZ7x7fFcdJP3h8d8DDevxFtlqRyvI8Lv0kfS3u1sn26/f3pRYC4+60ibhUFlvbE3FTdpF3vqWuCVPW7c7DO5ktes3eiydNnz5r9mfMsJppjd/7AhB4n8LOfTFWEM9ohAtoAH6zwzb911J4vlmZ1QM+4UlVrhfLTf7lJijqrvlA9KPbw3DKyAczrKLAhB1a9JRYj/A9zR/O4q3m2IjVNzPLcS1xi3keevGbo+8QJM898kF5H98elnN4fFDu0x/yrPcUYLeJ7d0qwo7Ce6zKJ9CKaSzu7GkjafJRSiS6LGbQRK+vmzZfMLOMX/+i8qQsaLyuwRfZsjjPm/ZN9TZHDE3K8uvHrNZPbppZ+f/mwLUACW4MEm4K2jYFnMvLrJ7Os3prkb27874ufDfSYXQ3YvP/qcDtZ4X6vYDrg2agG0S9B7BvNjAyDuIPN3oJ/cOvEYp9rfBn0I7dnhkxmvcKeT64Nwu0Q9NvOMjp+53dGesHOIPxjViJzz6aTSqaW2HkaKgwEPpsiHxioIeCiJ+9sChE0/d1boqFeuHTz07o07fwxDHrpc0/E682xYUDgWz0Mp8GvGLbnC3PK8O0HYxMk456+yJvsxkx0nHdFufZtKWvp3nTcJ7oJ7NyTU1OF5N8drb8ct2u1i0NOV9MymufGGD9Tf1zfBfi/PjLFecwNwzh1kMgNAsaQv7l8sm6KGcW72cR4zgAAjKlFghz2cISXVxbSC+q5S0BKfmeGlXwJl+sKF2bN18uX2eX+TBuN9MwpNjjp0V2UWcLn4LyiWLyOqOevS6oA/8N1x/9SexKix9H/08AAAD//zKhNapxGQAA"; }
        }
    }
}
