// <auto-generated />
namespace MvcBookStore.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Initial : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201204020747095_Initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/soy8up0+q6u3rtqrz8Xfzyfhp1maTrMk/So/LIiOEXufl+Xtit/MQ2H1k+6WeTwnD9vrN9Srn3j/7CL36LajN75VfBx/QRy/rapXX7fWr/Nx772z2UXo3fPdu92X7auc9oPDZR2fL9t7eR+mLdVlmk5I+OM9KjHn16SMmxef5Mq+zNp+9zNo2r2mOzmY5D0FJ8Wj16e2o8fDuzh6ocTdbLqs2a2nCe8h3UH1TtGVuMH3d1sQ8H6XPinf57Hm+vGjnFtsvsnfmE/r1o/SrZUG8Ri+19Tr3Ryd/b+71eN3Oq/pmEvlQHt9187pxtgX415lvh9b7zvhtB/T/ijl/VtRNi19/6PP+PPuhdLyZVUhltVlB9FekfLX0dIJv83dth33kzdd560l481HquhHdNWZN0yVC92VhltjryrrRwVi0nYq9KzrW6OK7A8r48RfZakV09pSzfpK+Fs18sv36/dXuQmDcnTYR7WuxtT0RebOLvPMtdU2YMkM6Y3AyW/SavdckmT79uepKv6O9aY3f+xwRGCqZ3w4oR85nNMIFiTEPVodK6MQMkL74epqVWT1gPk6qcr1YbjJFm6CoZveB6Ee3h+HUmg9mSE0ynLsdWnTp7ommtuyo2u4s3mqOjUh9M7McsyAM7qZ5Hnrxm6PvECRPp/ugvI9vD8tpaR+U+/SHPOs9BdhtYnu3irCj8B6r8rnZRe1pI2nyUUokuixm0ESvr5s2XzCzjF//ovKkLGi8rsEX2bI4z5v2TfU2h7tNyvLru7fWuDfNrPx/s49bgAQ3ejYb/bt+F4FvurzM6uk8q7cW2bs77+t3dN0zRvf/P97mzwr1e17iB81A1/N7D2Dv5831/YkBA+LLzZAjJ9L/2UezSUWIC4Lq+t3Kx9vg4sVAW8fwa/p/fTX3+K4frz9+mjfFhQOB6H2ZTxEzOKCmzdnyvDKTSOPyMTJNOnP8Rd5mM6L6cd0W59m0pa+nedOwh/+TWbmmJqeLST47W365blfr9rhp8sWkvPbH+/ju5v7ZyQ1xfvzlCn95ev3rD4HQLGgI+ZfLJ+uinFm8n0U0xAAIMKCKIWFFEQ6Bu7i2kF5Uy1sCUvI9zVf5EkL8Jl+sSgLWfLl8nV3mw7jdTMOQYo+fFtlFnS18CsonisnrjHr2uqAO/Ddcf/QnsSsli47+nwAAAP//5/YweKESAAA="; }
        }
    }
}
